//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Coop.Resources
{
    using System;


    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Messages
    {

        private static global::System.Resources.ResourceManager resourceMan;

        private static global::System.Globalization.CultureInfo resourceCulture;

        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Messages()
        {
        }

        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager
        {
            get
            {
                if (object.ReferenceEquals(resourceMan, null))
                {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Coop.Resources.Messages", typeof(Messages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }

        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture
        {
            get
            {
                return resourceCulture;
            }
            set
            {
                resourceCulture = value;
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to อายุไม่อยู่ในช่วงทำประกัน.
        /// </summary>
        public static string AgeNotProduct
        {
            get
            {
                return ResourceManager.GetString("AgeNotProduct", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Age not match.
        /// </summary>
        public static string AgePersonalNotAgeProduct
        {
            get
            {
                return ResourceManager.GetString("AgePersonalNotAgeProduct", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Text input allow only English alphabet characters (A-Z or a-z) and numbers (0-9).
        /// </summary>
        public static string AlphabetEnglishNumber
        {
            get
            {
                return ResourceManager.GetString("AlphabetEnglishNumber", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Text input allow only English alphabet characters (A-Z or a-z).
        /// </summary>
        public static string AlphabetEnglishOnly
        {
            get
            {
                return ResourceManager.GetString("AlphabetEnglishOnly", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Text input not allow only commar alphabet characters (,).
        /// </summary>
        public static string AlphabetNotAllowCommars
        {
            get
            {
                return ResourceManager.GetString("AlphabetNotAllowCommars", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Text input allow only numbers (0-9).
        /// </summary>
        public static string AlphabetNumber
        {
            get
            {
                return ResourceManager.GetString("AlphabetNumber", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Text input allow only Thai and English alphabet characters.
        /// </summary>
        public static string AlphabetThaiEnglish
        {
            get
            {
                return ResourceManager.GetString("AlphabetThaiEnglish", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Text input allow only Thai and English alphabet characters and numbers (0-9).
        /// </summary>
        public static string AlphabetThaiEnglishNumber
        {
            get
            {
                return ResourceManager.GetString("AlphabetThaiEnglishNumber", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Text input allow only Thai alphabet characters.
        /// </summary>
        public static string AlphabetThaiOnly
        {
            get
            {
                return ResourceManager.GetString("AlphabetThaiOnly", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Please fill in your answers.
        /// </summary>
        public static string AnswerRequired
        {
            get
            {
                return ResourceManager.GetString("AnswerRequired", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Please input Bank name.
        /// </summary>
        public static string ApporoveCode
        {
            get
            {
                return ResourceManager.GetString("ApporoveCode", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Please select Bank name.
        /// </summary>
        public static string BankChoose
        {
            get
            {
                return ResourceManager.GetString("BankChoose", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Please input Bank name.
        /// </summary>
        public static string BankNameRequired
        {
            get
            {
                return ResourceManager.GetString("BankNameRequired", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to The age of benificiary is between {0} to {1}..
        /// </summary>
        public static string BenefitAgeRange
        {
            get
            {
                return ResourceManager.GetString("BenefitAgeRange", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to The total for all beneficiaries less 100%..
        /// </summary>
        public static string BenefitSharedless100
        {
            get
            {
                return ResourceManager.GetString("BenefitSharedless100", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to The total for all beneficiaries must equal 100%..
        /// </summary>
        public static string BenefitSharedMoreThan100
        {
            get
            {
                return ResourceManager.GetString("BenefitSharedMoreThan100", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to BillingCode Required.
        /// </summary>
        public static string BillingCodeRequired
        {
            get
            {
                return ResourceManager.GetString("BillingCodeRequired", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Invalid birthday given (Invalid date/month/year)..
        /// </summary>
        public static string BirthDateOverDateNow
        {
            get
            {
                return ResourceManager.GetString("BirthDateOverDateNow", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to dd/mm/yyyy.
        /// </summary>
        public static string BirthDateThaiFormat
        {
            get
            {
                return ResourceManager.GetString("BirthDateThaiFormat", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Cannot add leads because this is on a blacklist..
        /// </summary>
        public static string BlackListData
        {
            get
            {
                return ResourceManager.GetString("BlackListData", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Please input the number of calls (1 - 99).
        /// </summary>
        public static string CallCountRange
        {
            get
            {
                return ResourceManager.GetString("CallCountRange", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Please select call status.
        /// </summary>
        public static string CallStatusAfterRequired
        {
            get
            {
                return ResourceManager.GetString("CallStatusAfterRequired", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Please input Call Status.
        /// </summary>
        public static string CallStatusConvertNameRequired
        {
            get
            {
                return ResourceManager.GetString("CallStatusConvertNameRequired", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Please input Call Status name (Eng).
        /// </summary>
        public static string CallStatusEnRequired
        {
            get
            {
                return ResourceManager.GetString("CallStatusEnRequired", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Please input Call Status.
        /// </summary>
        public static string CallStatusNameRequired
        {
            get
            {
                return ResourceManager.GetString("CallStatusNameRequired", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Please input Call Status name (Thai).
        /// </summary>
        public static string CallStatusThRequired
        {
            get
            {
                return ResourceManager.GetString("CallStatusThRequired", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Please select campaign.
        /// </summary>
        public static string CampaignChoose
        {
            get
            {
                return ResourceManager.GetString("CampaignChoose", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Please input the campaign name.
        /// </summary>
        public static string CampaignNameRequired
        {
            get
            {
                return ResourceManager.GetString("CampaignNameRequired", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Cannot Call. Please contact officer..
        /// </summary>
        public static string CannotCall
        {
            get
            {
                return ResourceManager.GetString("CannotCall", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to This list can not make a telephone call.
        /// </summary>
        public static string CantCall
        {
            get
            {
                return ResourceManager.GetString("CantCall", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Please, choose {0}..
        /// </summary>
        public static string Choose
        {
            get
            {
                return ResourceManager.GetString("Choose", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Please, Select 2 or more files..
        /// </summary>
        public static string Choose2Files
        {
            get
            {
                return ResourceManager.GetString("Choose2Files", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Please select  Campaign and ListLot..
        /// </summary>
        public static string ChooseCampaignAndListLot
        {
            get
            {
                return ResourceManager.GetString("ChooseCampaignAndListLot", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Please, select the answer..
        /// </summary>
        public static string ChoosedAnswer
        {
            get
            {
                return ResourceManager.GetString("ChoosedAnswer", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Please, choose listlot..
        /// </summary>
        public static string ChooseListlot
        {
            get
            {
                return ResourceManager.GetString("ChooseListlot", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to delete the data ?.
        /// </summary>
        public static string ConfirmDelete
        {
            get
            {
                return ResourceManager.GetString("ConfirmDelete", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to save the data ?.
        /// </summary>
        public static string ConfirmSave
        {
            get
            {
                return ResourceManager.GetString("ConfirmSave", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Control name must be a string with a maximum length of 50.
        /// </summary>
        public static string ControlNameMaxLength
        {
            get
            {
                return ResourceManager.GetString("ControlNameMaxLength", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Please input the control name.
        /// </summary>
        public static string ControlNameRequired
        {
            get
            {
                return ResourceManager.GetString("ControlNameRequired", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Copy To AddressRegistered..
        /// </summary>
        public static string CopyToAddressRegistered
        {
            get
            {
                return ResourceManager.GetString("CopyToAddressRegistered", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Copy To ContactAddress..
        /// </summary>
        public static string CopyToContactAddress
        {
            get
            {
                return ResourceManager.GetString("CopyToContactAddress", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Copy To Other Address.
        /// </summary>
        public static string CopyToOtherAddress
        {
            get
            {
                return ResourceManager.GetString("CopyToOtherAddress", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Credit card number is invalid..
        /// </summary>
        public static string CreditAccountFormat
        {
            get
            {
                return ResourceManager.GetString("CreditAccountFormat", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to &apos;The Credit Card Number does not match the Credit Card Type.
        /// </summary>
        public static string creditAccountIsNotCreditType
        {
            get
            {
                return ResourceManager.GetString("creditAccountIsNotCreditType", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Please input your credit card number.
        /// </summary>
        public static string CreditAccountRequired
        {
            get
            {
                return ResourceManager.GetString("CreditAccountRequired", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Please input your first 6 digits credit card number..
        /// </summary>
        public static string CreditAccountRequiredSixDigit
        {
            get
            {
                return ResourceManager.GetString("CreditAccountRequiredSixDigit", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to The first 6 digits of your credit cards are duplicate.
        /// </summary>
        public static string CreditAccountSixDuplicate
        {
            get
            {
                return ResourceManager.GetString("CreditAccountSixDuplicate", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to The first 6 digits of your credit cards could not be found..
        /// </summary>
        public static string CreditAccountSixNotFound
        {
            get
            {
                return ResourceManager.GetString("CreditAccountSixNotFound", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Credit expired less than current day.
        /// </summary>
        public static string CreditExpired
        {
            get
            {
                return ResourceManager.GetString("CreditExpired", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Please select credit card type.
        /// </summary>
        public static string CreditTypeChoose
        {
            get
            {
                return ResourceManager.GetString("CreditTypeChoose", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Please input Credit Type Name (Thai).
        /// </summary>
        public static string CreditTypeNameRequiredThai
        {
            get
            {
                return ResourceManager.GetString("CreditTypeNameRequiredThai", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Delete Complete..
        /// </summary>
        public static string DeleteComplete
        {
            get
            {
                return ResourceManager.GetString("DeleteComplete", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to An error occurred while deleting, Please try again..
        /// </summary>
        public static string DeleteError
        {
            get
            {
                return ResourceManager.GetString("DeleteError", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Text description limit to 100 characters.
        /// </summary>
        public static string DescriptionMaxLength
        {
            get
            {
                return ResourceManager.GetString("DescriptionMaxLength", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Please input description.
        /// </summary>
        public static string DescriptionRequired
        {
            get
            {
                return ResourceManager.GetString("DescriptionRequired", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to District code limit to 5 characters.
        /// </summary>
        public static string DistrictCodeMaxLength
        {
            get
            {
                return ResourceManager.GetString("DistrictCodeMaxLength", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to District name limit to 50 characters.
        /// </summary>
        public static string DistrictNameMaxLength
        {
            get
            {
                return ResourceManager.GetString("DistrictNameMaxLength", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Please input district.
        /// </summary>
        public static string DistrictRequired
        {
            get
            {
                return ResourceManager.GetString("DistrictRequired", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to {0} is duplication..
        /// </summary>
        public static string Duplicate
        {
            get
            {
                return ResourceManager.GetString("Duplicate", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Duplicate Product.
        /// </summary>
        public static string DuplicateProduct
        {
            get
            {
                return ResourceManager.GetString("DuplicateProduct", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Duplicate Name Exists..
        /// </summary>
        public static string DupName
        {
            get
            {
                return ResourceManager.GetString("DupName", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Email format is invalid..
        /// </summary>
        public static string EmailFormat
        {
            get
            {
                return ResourceManager.GetString("EmailFormat", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Employee name limit to 30 characters..
        /// </summary>
        public static string EmployeeFirstNameMaxLength
        {
            get
            {
                return ResourceManager.GetString("EmployeeFirstNameMaxLength", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Employee lastName must be a string with a maximum length of 30..
        /// </summary>
        public static string EmployeeLastNameMaxLength
        {
            get
            {
                return ResourceManager.GetString("EmployeeLastNameMaxLength", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to LeadSourceDuplicate..
        /// </summary>
        public static string LeadSourceDuplicate
        {
            get
            {
                return ResourceManager.GetString("LeadSourceDuplicate", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Please, input LeadSource..
        /// </summary>
        public static string LeadSourceRequire
        {
            get
            {
                return ResourceManager.GetString("LeadSourceRequire", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Please, selected employee receive list..
        /// </summary>
        public static string EmployeeReceiveList
        {
            get
            {
                return ResourceManager.GetString("EmployeeReceiveList", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Please, choose employee type..
        /// </summary>
        public static string EmployeeTypeChoose
        {
            get
            {
                return ResourceManager.GetString("EmployeeTypeChoose", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Please, input enddate..
        /// </summary>
        public static string EndDateRequired
        {
            get
            {
                return ResourceManager.GetString("EndDateRequired", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Enter more text.
        /// </summary>
        public static string Entermoretext
        {
            get
            {
                return ResourceManager.GetString("Entermoretext", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Please, input fax phone number only..
        /// </summary>
        public static string FaxPhoneNumberOnly
        {
            get
            {
                return ResourceManager.GetString("FaxPhoneNumberOnly", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Firstname must be a string with a maximum length of 50.
        /// </summary>
        public static string FirstNameMaxLength
        {
            get
            {
                return ResourceManager.GetString("FirstNameMaxLength", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Input alphabet English only..
        /// </summary>
        public static string forAlphabetEnglish
        {
            get
            {
                return ResourceManager.GetString("forAlphabetEnglish", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Input alphabet Thai and English only..
        /// </summary>
        public static string forAlphabetThaiAndEnglish
        {
            get
            {
                return ResourceManager.GetString("forAlphabetThaiAndEnglish", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Input alphabet Thai, English, mark points 1 point and only 2 spaces..
        /// </summary>
        public static string forAlphabetThaiAndEnglishLastName
        {
            get
            {
                return ResourceManager.GetString("forAlphabetThaiAndEnglishLastName", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Please,input 4 charactor for Booth.
        /// </summary>
        public static string FourChar
        {
            get
            {
                return ResourceManager.GetString("FourChar", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Gender not match.
        /// </summary>
        public static string GenderPersonalNotGenderProduct
        {
            get
            {
                return ResourceManager.GetString("GenderPersonalNotGenderProduct", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Higher criterion..
        /// </summary>
        public static string HigherCriterion
        {
            get
            {
                return ResourceManager.GetString("HigherCriterion", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Please, input home phone number only..
        /// </summary>
        public static string HomePhoneNumberOnly
        {
            get
            {
                return ResourceManager.GetString("HomePhoneNumberOnly", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to The {0} provided is incorrect..
        /// </summary>
        public static string Incorrect
        {
            get
            {
                return ResourceManager.GetString("Incorrect", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Please input the number of transfer list..
        /// </summary>
        public static string InputNumList
        {
            get
            {
                return ResourceManager.GetString("InputNumList", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Insurance premiums are subject to change. Because age and insurance are don&apos;t relationships.
        /// </summary>
        public static string InsuranceAgeChange
        {
            get
            {
                return ResourceManager.GetString("InsuranceAgeChange", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Insurance premiums are subject to change..
        /// </summary>
        public static string Insure
        {
            get
            {
                return ResourceManager.GetString("Insure", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to The value must be less than {0}.
        /// </summary>
        public static string IsValueLessThan
        {
            get
            {
                return ResourceManager.GetString("IsValueLessThan", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to LastName must be a string with a maximum length of 50.
        /// </summary>
        public static string LastNameMaxLength
        {
            get
            {
                return ResourceManager.GetString("LastNameMaxLength", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Your license was.
        /// </summary>
        public static string License
        {
            get
            {
                return ResourceManager.GetString("License", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Please, choose listlot..
        /// </summary>
        public static string ListlotChoose
        {
            get
            {
                return ResourceManager.GetString("ListlotChoose", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Lower criterion..
        /// </summary>
        public static string LowerCriterion
        {
            get
            {
                return ResourceManager.GetString("LowerCriterion", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to {0} must be a string with length of {1}..
        /// </summary>
        public static string MaxLength
        {
            get
            {
                return ResourceManager.GetString("MaxLength", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Input maximum length of 50.
        /// </summary>
        public static string MaxLength50
        {
            get
            {
                return ResourceManager.GetString("MaxLength50", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Meet the criterion..
        /// </summary>
        public static string MeetCriterion
        {
            get
            {
                return ResourceManager.GetString("MeetCriterion", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Merge File must have 2 or more files selected..
        /// </summary>
        public static string Mergefile2Files
        {
            get
            {
                return ResourceManager.GetString("Mergefile2Files", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Please, input mobile phone number only..
        /// </summary>
        public static string MobilePhoneNumberOnly
        {
            get
            {
                return ResourceManager.GetString("MobilePhoneNumberOnly", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to More Than 0..
        /// </summary>
        public static string MoreThanZero
        {
            get
            {
                return ResourceManager.GetString("MoreThanZero", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to {0} Must Be {1}..
        /// </summary>
        public static string MustBe
        {
            get
            {
                return ResourceManager.GetString("MustBe", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Please select Transferor..
        /// </summary>
        public static string NoListFound
        {
            get
            {
                return ResourceManager.GetString("NoListFound", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Could not find this audio file..
        /// </summary>
        public static string NotAudioFile
        {
            get
            {
                return ResourceManager.GetString("NotAudioFile", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Not found {0}.
        /// </summary>
        public static string NotFound
        {
            get
            {
                return ResourceManager.GetString("NotFound", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Please, Check Product Plan..
        /// </summary>
        public static string NotSelectProductCategory
        {
            get
            {
                return ResourceManager.GetString("NotSelectProductCategory", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Can not input  &apos;, &quot;, |.
        /// </summary>
        public static string notsingledoubleQuote
        {
            get
            {
                return ResourceManager.GetString("notsingledoubleQuote", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Num of transfer list is over than filter list..
        /// </summary>
        public static string NumListOver
        {
            get
            {
                return ResourceManager.GetString("NumListOver", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Please, input objection group..
        /// </summary>
        public static string ObjectionGroupRequired
        {
            get
            {
                return ResourceManager.GetString("ObjectionGroupRequired", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Please, input occupation name..
        /// </summary>
        public static string OccupationNameRequired
        {
            get
            {
                return ResourceManager.GetString("OccupationNameRequired", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Please, input office phone number only..
        /// </summary>
        public static string OfficePhoneNumberOnly
        {
            get
            {
                return ResourceManager.GetString("OfficePhoneNumberOnly", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Online user exceed allowance ..
        /// </summary>
        public static string Onlineuserexceedallowance
        {
            get
            {
                return ResourceManager.GetString("Onlineuserexceedallowance", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Parent sort order is duplication..
        /// </summary>
        public static string ParentSortOrderDuplicate
        {
            get
            {
                return ResourceManager.GetString("ParentSortOrderDuplicate", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to The password provided is incorrect..
        /// </summary>
        public static string PassInChang
        {
            get
            {
                return ResourceManager.GetString("PassInChang", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Password And ConfirmPassword Are Mismatch..
        /// </summary>
        public static string PasswordAndConfirmNotMatch
        {
            get
            {
                return ResourceManager.GetString("PasswordAndConfirmNotMatch", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Password must be a string with a minimum length of 8 and a maximum length of 16..
        /// </summary>
        public static string PasswordMaxLength
        {
            get
            {
                return ResourceManager.GetString("PasswordMaxLength", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Password not match..
        /// </summary>
        public static string PasswordNotMatch
        {
            get
            {
                return ResourceManager.GetString("PasswordNotMatch", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Please, input PaymentTypeCode..
        /// </summary>
        public static string PaymentTypeCodeRequired
        {
            get
            {
                return ResourceManager.GetString("PaymentTypeCodeRequired", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Please, input payment type name..
        /// </summary>
        public static string PaymentTypeNameRequired
        {
            get
            {
                return ResourceManager.GetString("PaymentTypeNameRequired", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to person.
        /// </summary>
        public static string Person
        {
            get
            {
                return ResourceManager.GetString("Person", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Please, input phone status name..
        /// </summary>
        public static string PhoneStatusNameRequired
        {
            get
            {
                return ResourceManager.GetString("PhoneStatusNameRequired", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Please select the file types \&quot;.xls\&quot; or \&quot;.xlsx\&quot;..
        /// </summary>
        public static string PleaseSelectExcelFile
        {
            get
            {
                return ResourceManager.GetString("PleaseSelectExcelFile", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Policy number is empty..
        /// </summary>
        public static string PolicyNumberIsEmpty
        {
            get
            {
                return ResourceManager.GetString("PolicyNumberIsEmpty", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Policy number is used..
        /// </summary>
        public static string PolicyNumberIsUsed
        {
            get
            {
                return ResourceManager.GetString("PolicyNumberIsUsed", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Fill in policy status.
        /// </summary>
        public static string PolicyStatusNameRequired
        {
            get
            {
                return ResourceManager.GetString("PolicyStatusNameRequired", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to กรุณากรอกรหัสไปรษณีย์ 5 หลัก ด้วยตัวเลข 0-9.
        /// </summary>
        public static string PostCodeChkLength
        {
            get
            {
                return ResourceManager.GetString("PostCodeChkLength", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Postcode must be a string with a maximum length of 5.
        /// </summary>
        public static string PostCodeMaxLength
        {
            get
            {
                return ResourceManager.GetString("PostCodeMaxLength", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Please, input postcode..
        /// </summary>
        public static string PostCodeRequired
        {
            get
            {
                return ResourceManager.GetString("PostCodeRequired", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Please, choose priority phone..
        /// </summary>
        public static string PriorityPhoneNull
        {
            get
            {
                return ResourceManager.GetString("PriorityPhoneNull", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Please, input Product Plan Type Name..
        /// </summary>
        public static string ProductPlanTypeName
        {
            get
            {
                return ResourceManager.GetString("ProductPlanTypeName", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to ทุนประกันจะต้องอยู่ในช่วง 50,000 บาท ถึง 300,000 บาท.
        /// </summary>
        public static string ProtectAmount50UP
        {
            get
            {
                return ResourceManager.GetString("ProtectAmount50UP", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to ทุนประกันจะต้องอยู่ในช่วง 50,000 บาท ถึง 200,000 บาท.
        /// </summary>
        public static string ProtectAmountGIWL
        {
            get
            {
                return ResourceManager.GetString("ProtectAmountGIWL", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Province code must be a string with a maximum length of 4.
        /// </summary>
        public static string ProvinceCodeMaxLength
        {
            get
            {
                return ResourceManager.GetString("ProvinceCodeMaxLength", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Province name must be a string with a maximum length of 50.
        /// </summary>
        public static string ProvinceNameMaxLength
        {
            get
            {
                return ResourceManager.GetString("ProvinceNameMaxLength", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Please, input province..
        /// </summary>
        public static string ProvinceRequired
        {
            get
            {
                return ResourceManager.GetString("ProvinceRequired", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Question must be a string with a maximum length of 1000.
        /// </summary>
        public static string QuestionMaxLength
        {
            get
            {
                return ResourceManager.GetString("QuestionMaxLength", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Please, answers {0}&apos;s health question.
        /// </summary>
        public static string QuestionProductRequired
        {
            get
            {
                return ResourceManager.GetString("QuestionProductRequired", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Please, input question..
        /// </summary>
        public static string QuestionRequired1
        {
            get
            {
                return ResourceManager.GetString("QuestionRequired1", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Please, input Question Type Description..
        /// </summary>
        public static string QuestionTypeDescription
        {
            get
            {
                return ResourceManager.GetString("QuestionTypeDescription", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Please, input Question Type Name..
        /// </summary>
        public static string QuestionTypeName
        {
            get
            {
                return ResourceManager.GetString("QuestionTypeName", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Reference No MaxLength.
        /// </summary>
        public static string ReferenceNoMaxLength
        {
            get
            {
                return ResourceManager.GetString("ReferenceNoMaxLength", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Reference No Required.
        /// </summary>
        public static string ReferenceNoRequired
        {
            get
            {
                return ResourceManager.GetString("ReferenceNoRequired", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to PleaseSelect ReportTo..
        /// </summary>
        public static string ReportToRequired
        {
            get
            {
                return ResourceManager.GetString("ReportToRequired", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Please, input {0}..
        /// </summary>
        public static string Required
        {
            get
            {
                return ResourceManager.GetString("Required", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Please input all report parameters..
        /// </summary>
        public static string RequiredAllParameter
        {
            get
            {
                return ResourceManager.GetString("RequiredAllParameter", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Please, input the answer..
        /// </summary>
        public static string RequiredAnswer
        {
            get
            {
                return ResourceManager.GetString("RequiredAnswer", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Please, input ApporoveCode..
        /// </summary>
        public static string RequiredApporoveCode
        {
            get
            {
                return ResourceManager.GetString("RequiredApporoveCode", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Please check the information..
        /// </summary>
        public static string Requiredbtncopy
        {
            get
            {
                return ResourceManager.GetString("Requiredbtncopy", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Require Memo.
        /// </summary>
        public static string RequiredMemo
        {
            get
            {
                return ResourceManager.GetString("RequiredMemo", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to You put phone number less than 1 number..
        /// </summary>
        public static string RequiredMobilePhoneNumber1
        {
            get
            {
                return ResourceManager.GetString("RequiredMobilePhoneNumber1", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Require Reconfrim Status.
        /// </summary>
        public static string RequiredReconfirmStatusID
        {
            get
            {
                return ResourceManager.GetString("RequiredReconfirmStatusID", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Please, input the specific answer..
        /// </summary>
        public static string RequiredSpecificAnswer
        {
            get
            {
                return ResourceManager.GetString("RequiredSpecificAnswer", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to ReserveCode1 Required.
        /// </summary>
        public static string ReserveCode1Required
        {
            get
            {
                return ResourceManager.GetString("ReserveCode1Required", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Save Complete..
        /// </summary>
        public static string SaveComplete
        {
            get
            {
                return ResourceManager.GetString("SaveComplete", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Select {0} ....
        /// </summary>
        public static string Select
        {
            get
            {
                return ResourceManager.GetString("Select", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Please, select answer no {0}..
        /// </summary>
        public static string SelectAnswer
        {
            get
            {
                return ResourceManager.GetString("SelectAnswer", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Please, Select an audio file before Merge file..
        /// </summary>
        public static string SelectMergeFile
        {
            get
            {
                return ResourceManager.GetString("SelectMergeFile", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to please contact your software vendor..
        /// </summary>
        public static string Software
        {
            get
            {
                return ResourceManager.GetString("Software", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Sort order is duplication..
        /// </summary>
        public static string SortOrderDuplicate
        {
            get
            {
                return ResourceManager.GetString("SortOrderDuplicate", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to SortOrder is over curent max value..
        /// </summary>
        public static string SortOrderOverMax
        {
            get
            {
                return ResourceManager.GetString("SortOrderOverMax", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Please, input sort order..
        /// </summary>
        public static string SortOrderRequired
        {
            get
            {
                return ResourceManager.GetString("SortOrderRequired", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Spouse could have only one person..
        /// </summary>
        public static string SpouseMax
        {
            get
            {
                return ResourceManager.GetString("SpouseMax", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Please, input start date..
        /// </summary>
        public static string StartDateRequired
        {
            get
            {
                return ResourceManager.GetString("StartDateRequired", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to The status is incorrect..
        /// </summary>
        public static string Statusnotformat
        {
            get
            {
                return ResourceManager.GetString("Statusnotformat", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Subdistrict code must be a string with a maximum length of 5.
        /// </summary>
        public static string SubDistrictCodeMaxLength
        {
            get
            {
                return ResourceManager.GetString("SubDistrictCodeMaxLength", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Subdistrict name must be a string with a maximum length of 50.
        /// </summary>
        public static string SubDistrictNameMaxLength
        {
            get
            {
                return ResourceManager.GetString("SubDistrictNameMaxLength", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Please, input subdistrict..
        /// </summary>
        public static string SubDistrictRequired
        {
            get
            {
                return ResourceManager.GetString("SubDistrictRequired", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Subscribe success..
        /// </summary>
        public static string SubscribeSuccess
        {
            get
            {
                return ResourceManager.GetString("SubscribeSuccess", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Subscribe fail..
        /// </summary>
        public static string SubscribeUnsuccess
        {
            get
            {
                return ResourceManager.GetString("SubscribeUnsuccess", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Please, choose title name..
        /// </summary>
        public static string TitleChoose
        {
            get
            {
                return ResourceManager.GetString("TitleChoose", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Please, input title name..
        /// </summary>
        public static string TitleRequired
        {
            get
            {
                return ResourceManager.GetString("TitleRequired", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to to.
        /// </summary>
        public static string To
        {
            get
            {
                return ResourceManager.GetString("To", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Transfer List Fail..
        /// </summary>
        public static string TransferFail
        {
            get
            {
                return ResourceManager.GetString("TransferFail", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Transfer List Successfully..
        /// </summary>
        public static string TransferSuccess
        {
            get
            {
                return ResourceManager.GetString("TransferSuccess", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to The url is incorrect..
        /// </summary>
        public static string Urlnotformat
        {
            get
            {
                return ResourceManager.GetString("Urlnotformat", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Your user account has been disabled, User Date Expried..
        /// </summary>
        public static string UserisExpired
        {
            get
            {
                return ResourceManager.GetString("UserisExpired", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Your user account has been disabled, because wrong password more than once..
        /// </summary>
        public static string UserisLockedout
        {
            get
            {
                return ResourceManager.GetString("UserisLockedout", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Your user account has been disabled..
        /// </summary>
        public static string UserisnotActive
        {
            get
            {
                return ResourceManager.GetString("UserisnotActive", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Your user account has online..
        /// </summary>
        public static string UserisnotOnline
        {
            get
            {
                return ResourceManager.GetString("UserisnotOnline", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to The user name or password provided is incorrect..
        /// </summary>
        public static string UserNameAndPassIncorrect
        {
            get
            {
                return ResourceManager.GetString("UserNameAndPassIncorrect", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to The user name with password is not on this System..
        /// </summary>
        public static string UserNameAndPasswordnotonSystem
        {
            get
            {
                return ResourceManager.GetString("UserNameAndPasswordnotonSystem", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Don&apos;t create userName duplicate with password..
        /// </summary>
        public static string UserNameMatchPassword
        {
            get
            {
                return ResourceManager.GetString("UserNameMatchPassword", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Username must be a string with a maximum length of 20..
        /// </summary>
        public static string UserNameMaxLength
        {
            get
            {
                return ResourceManager.GetString("UserNameMaxLength", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Weight over height..
        /// </summary>
        public static string WeightOverHeight
        {
            get
            {
                return ResourceManager.GetString("WeightOverHeight", resourceCulture);
            }
        }
    }
}
