//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Coop.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Text {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Text() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Coop.Resources.Text", typeof(Text).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Access Permission.
        /// </summary>
        public static string AccessPermission {
            get {
                return ResourceManager.GetString("AccessPermission", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Account Name.
        /// </summary>
        //public static string AccountName {
        //    get {
        //        return ResourceManager.GetString("AccountName", resourceCulture);
        //    }
        //}
        
        /// <summary>
        ///   Looks up a localized string similar to Account Number.
        /// </summary>
        //public static string AccountNumber {
        //    get {
        //        return ResourceManager.GetString("AccountNumber", resourceCulture);
        //    }
        //}
        
        /// <summary>
        ///   Looks up a localized string similar to Age.
        /// </summary>
        //public static string Age {
        //    get {
        //        return ResourceManager.GetString("Age", resourceCulture);
        //    }
        //}
        
        /// <summary>
        ///   Looks up a localized string similar to Bank.
        /// </summary>
        //public static string Bank {
        //    get {
        //        return ResourceManager.GetString("Bank", resourceCulture);
        //    }
        //}
        
        /// <summary>
        ///   Looks up a localized string similar to Account Name.
        /// </summary>
        //public static string BankAccountName {
        //    get {
        //        return ResourceManager.GetString("BankAccountName", resourceCulture);
        //    }
        //}
        
        /// <summary>
        ///   Looks up a localized string similar to Account Number.
        /// </summary>
        //public static string BankAccountNumber {
        //    get {
        //        return ResourceManager.GetString("BankAccountNumber", resourceCulture);
        //    }
        //}
        
        /// <summary>
        ///   Looks up a localized string similar to Account Type.
        /// </summary>
        //public static string BankAccountType {
        //    get {
        //        return ResourceManager.GetString("BankAccountType", resourceCulture);
        //    }
        //}
        
        /// <summary>
        ///   Looks up a localized string similar to BirthDate(Thai).
        /// </summary>
        //public static string BirthDateThai {
        //    get {
        //        return ResourceManager.GetString("BirthDateThai", resourceCulture);
        //    }
        //}
        
        /// <summary>
        ///   Looks up a localized string similar to BMI.
        /// </summary>
        //public static string BMI {
        //    get {
        //        return ResourceManager.GetString("BMI", resourceCulture);
        //    }
        //}
        
        /// <summary>
        ///   Looks up a localized string similar to Change Password.
        /// </summary>
        //public static string ChangePassword {
        //    get {
        //        return ResourceManager.GetString("ChangePassword", resourceCulture);
        //    }
        //}
        
        /// <summary>
        ///   Looks up a localized string similar to Clear.
        /// </summary>
        //public static string Clear {
        //    get {
        //        return ResourceManager.GetString("Clear", resourceCulture);
        //    }
        //}
        
        /// <summary>
        ///   Looks up a localized string similar to Close.
        /// </summary>
        //public static string Close {
        //    get {
        //        return ResourceManager.GetString("Close", resourceCulture);
        //    }
        //}
        
        /// <summary>
        ///   Looks up a localized string similar to Female.
        /// </summary>
        //public static string Female {
        //    get {
        //        return ResourceManager.GetString("Female", resourceCulture);
        //    }
        //}
        
        /// <summary>
        ///   Looks up a localized string similar to First Name.
        /// </summary>
        //public static string FirstName {
        //    get {
        //        return ResourceManager.GetString("FirstName", resourceCulture);
        //    }
        //}
        
        /// <summary>
        ///   Looks up a localized string similar to Gender.
        /// </summary>
        //public static string Gender {
        //    get {
        //        return ResourceManager.GetString("Gender", resourceCulture);
        //    }
        //}
        
        /// <summary>
        ///   Looks up a localized string similar to Height.
        /// </summary>
        //public static string Height {
        //    get {
        //        return ResourceManager.GetString("Height", resourceCulture);
        //    }
        //}
        
        /// <summary>
        ///   Looks up a localized string similar to Home.
        /// </summary>
        public static string Home {
            get {
                return ResourceManager.GetString("Home", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ID Card.
        /// </summary>
        public static string IDCard {
            get {
                return ResourceManager.GetString("IDCard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Income.
        /// </summary>
        //public static string Income {
        //    get {
        //        return ResourceManager.GetString("Income", resourceCulture);
        //    }
        //}
        
        /// <summary>
        ///   Looks up a localized string similar to Active.
        /// </summary>
        public static string IsActive {
            get {
                return ResourceManager.GetString("IsActive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last Name.
        /// </summary>
        //public static string LastName {
        //    get {
        //        return ResourceManager.GetString("LastName", resourceCulture);
        //    }
        //}
        
        /// <summary>
        ///   Looks up a localized string similar to Log Out.
        /// </summary>
        public static string LogOut {
            get {
                return ResourceManager.GetString("LogOut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Male.
        /// </summary>
        //public static string Male {
        //    get {
        //        return ResourceManager.GetString("Male", resourceCulture);
        //    }
        //}
        
        /// <summary>
        ///   Looks up a localized string similar to Max Lenght.
        /// </summary>
        //public static string MaxLenght {
        //    get {
        //        return ResourceManager.GetString("MaxLenght", resourceCulture);
        //    }
        //}
        
        /// <summary>
        ///   Looks up a localized string similar to Modified By.
        /// </summary>
        public static string ModifiedBy {
            get {
                return ResourceManager.GetString("ModifiedBy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Modified Date.
        /// </summary>
        public static string ModifiedDate {
            get {
                return ResourceManager.GetString("ModifiedDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Module Name.
        /// </summary>
        public static string ModuleName {
            get {
                return ResourceManager.GetString("ModuleName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        public static string Name {
            get {
                return ResourceManager.GetString("Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Occupation.
        /// </summary>
        //public static string Occupation {
        //    get {
        //        return ResourceManager.GetString("Occupation", resourceCulture);
        //    }
        //}
        
        /// <summary>
        ///   Looks up a localized string similar to Password.
        /// </summary>
        public static string Password {
            get {
                return ResourceManager.GetString("Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please, input password..
        /// </summary>
        public static string PasswordRequired {
            get {
                return ResourceManager.GetString("PasswordRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Coop.
        /// </summary>
        public static string ProgramName {
            get {
                return ResourceManager.GetString("ProgramName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        public static string Save {
            get {
                return ResourceManager.GetString("Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sort Order.
        /// </summary>
        public static string SortOrder {
            get {
                return ResourceManager.GetString("SortOrder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Success.
        /// </summary>
        public static string Success {
            get {
                return ResourceManager.GetString("Success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Title.
        /// </summary>
        //public static string TitleName {
        //    get {
        //        return ResourceManager.GetString("TitleName", resourceCulture);
        //    }
        //}
        
        /// <summary>
        ///   Looks up a localized string similar to User Name.
        /// </summary>
        public static string UserName {
            get {
                return ResourceManager.GetString("UserName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Username or Password is Invalid.
        /// </summary>
        public static string UserNameOrPasswordInvalid {
            get {
                return ResourceManager.GetString("UserNameOrPasswordInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Weight.
        /// </summary>
        //public static string Weight {
        //    get {
        //        return ResourceManager.GetString("Weight", resourceCulture);
        //    }
        //}
    }
}
