//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Coop.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Deposit
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Deposit()
        {
            this.Item = new HashSet<Item>();
            this.NoBook = new HashSet<NoBook>();
            this.NoCard = new HashSet<NoCard>();
            this.TtlfDeposit = new HashSet<TtlfDeposit>();
        }
    
        public Nullable<int> CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<int> ModifiedBy { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public string Filestatus { get; set; }
        public int CoopID { get; set; }
        public string AccountNo { get; set; }
        public string DepositTypeID { get; set; }
        public string MemberID { get; set; }
        public string AccountName { get; set; }
        public string BookNo { get; set; }
        public Nullable<System.DateTime> OpenDate { get; set; }
        public Nullable<System.DateTime> LastContact { get; set; }
        public Nullable<System.DateTime> LastCalcInt { get; set; }
        public string IntType { get; set; }
        public Nullable<decimal> BFLedgerBal { get; set; }
        public Nullable<decimal> LedgerBal { get; set; }
        public Nullable<decimal> AvailBal { get; set; }
        public Nullable<decimal> BookBal { get; set; }
        public Nullable<decimal> AccInt { get; set; }
        public Nullable<int> LastLedgerLine { get; set; }
        public Nullable<int> LastBookLine { get; set; }
        public Nullable<int> BookPage { get; set; }
        public Nullable<int> HoldTypeID { get; set; }
        public Nullable<decimal> HoldAmt { get; set; }
        public Nullable<decimal> IntDueAmt { get; set; }
        public string BudgetYear { get; set; }
        public Nullable<decimal> UnpayInt { get; set; }
        public Nullable<int> BookSeq { get; set; }
        public Nullable<decimal> MonthDepAmt { get; set; }
        public Nullable<System.DateTime> MonthDepositDate { get; set; }
        public Nullable<decimal> MonthWithdrawAmt { get; set; }
        public Nullable<int> MonthWithdrawTimes { get; set; }
        public Nullable<decimal> Amt1 { get; set; }
        public Nullable<decimal> Amt2 { get; set; }
        public Nullable<decimal> Amt3 { get; set; }
    
        public virtual DepositType DepositType { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Item> Item { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<NoBook> NoBook { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<NoCard> NoCard { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TtlfDeposit> TtlfDeposit { get; set; }
    }
}
