//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Coop.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Interest
    {
        public Nullable<int> CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<int> ModifiedBy { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public string Filestatus { get; set; }
        public int CoopID { get; set; }
        public string Type { get; set; }
        public string TInt { get; set; }
        public System.DateTime FirstEffectDate { get; set; }
        public Nullable<System.DateTime> LastEffectDate { get; set; }
        public Nullable<decimal> Balance1 { get; set; }
        public Nullable<decimal> Rate1 { get; set; }
        public Nullable<decimal> ChargeRate1 { get; set; }
        public Nullable<decimal> Balance2 { get; set; }
        public Nullable<decimal> Rate2 { get; set; }
        public Nullable<decimal> ChargeRate2 { get; set; }
        public Nullable<decimal> Balance3 { get; set; }
        public Nullable<decimal> Rate3 { get; set; }
        public Nullable<decimal> ChargeRate3 { get; set; }
        public Nullable<decimal> Balance4 { get; set; }
        public Nullable<decimal> Rate4 { get; set; }
        public Nullable<decimal> ChargeRate4 { get; set; }
        public Nullable<decimal> Balance5 { get; set; }
        public Nullable<decimal> Rate5 { get; set; }
        public Nullable<decimal> ChargeRate5 { get; set; }
    }
}
