//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Coop.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Item
    {
        public Nullable<int> CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<int> ModifiedBy { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public string Filestatus { get; set; }
        public int CoopID { get; set; }
        public string AccountNo { get; set; }
        public int ItemNo { get; set; }
        public Nullable<System.DateTime> TxnDate { get; set; }
        public Nullable<System.DateTime> DepositDate { get; set; }
        public Nullable<decimal> DepositAmt { get; set; }
        public Nullable<decimal> DepositBal { get; set; }
        public Nullable<System.DateTime> DueDate { get; set; }
        public Nullable<decimal> IntDueAmt { get; set; }
        public Nullable<decimal> Tax { get; set; }
        public Nullable<int> ItemNoNew { get; set; }
        public Nullable<decimal> TempAccInt { get; set; }
    
        public virtual Deposit Deposit { get; set; }
    }
}
