//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Coop.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class LoanType
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public LoanType()
        {
            this.RequestLoan = new HashSet<RequestLoan>();
        }
    
        public Nullable<int> CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<int> ModifiedBy { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public string Filestatus { get; set; }
        public int CoopID { get; set; }
        public string LoanTypeID { get; set; }
        public string LoanTypeName { get; set; }
        public string IntType { get; set; }
        public Nullable<int> NoMemberMonths { get; set; }
        public Nullable<decimal> MinLoanAmt { get; set; }
        public Nullable<decimal> MaxLoanAmt { get; set; }
        public Nullable<bool> SecurityFlag { get; set; }
        public Nullable<int> CalcIntFlag { get; set; }
        public Nullable<int> NoOfLoanYears { get; set; }
        public Nullable<int> LastLoanID { get; set; }
        public string PrefixLoanID { get; set; }
        public Nullable<int> LastRequestNo { get; set; }
        public string PrefixRequestNo { get; set; }
        public Nullable<decimal> ChargeRate { get; set; }
        public Nullable<decimal> DiscIntRate { get; set; }
        public Nullable<int> DiscIntFlag { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RequestLoan> RequestLoan { get; set; }
    }
}
