//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Coop.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Loan
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Loan()
        {
            this.LoanDue = new HashSet<LoanDue>();
            this.MonthBalanceLoan = new HashSet<MonthBalanceLoan>();
            this.Security = new HashSet<Security>();
            this.TtlfLoan = new HashSet<TtlfLoan>();
        }
    
        public Nullable<int> CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<int> ModifiedBy { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public string Filestatus { get; set; }
        public int CoopID { get; set; }
        public string LoanID { get; set; }
        public string LoanTypeID { get; set; }
        public string MemberID { get; set; }
        public Nullable<System.DateTime> LoanDate { get; set; }
        public Nullable<System.DateTime> LastContact { get; set; }
        public Nullable<System.DateTime> StartCalcInt { get; set; }
        public Nullable<System.DateTime> LastCalcInt { get; set; }
        public Nullable<System.DateTime> LastCalcCharge { get; set; }
        public string IntType { get; set; }
        public Nullable<decimal> LoanAmt { get; set; }
        public Nullable<decimal> BFBal { get; set; }
        public Nullable<decimal> LoanBal { get; set; }
        public Nullable<decimal> BFInt { get; set; }
        public Nullable<decimal> BFUnpayInt { get; set; }
        public Nullable<decimal> UnpayInt { get; set; }
        public Nullable<decimal> BFCharge { get; set; }
        public Nullable<decimal> BFUnpayCharge { get; set; }
        public Nullable<decimal> UnpayCharge { get; set; }
        public Nullable<decimal> BFUnpayPrinciple { get; set; }
        public Nullable<decimal> UnpayPrinciple { get; set; }
        public Nullable<int> DiscIntFlag { get; set; }
        public Nullable<decimal> BFDiscInt { get; set; }
        public Nullable<decimal> BFUnpayDiscInt { get; set; }
        public Nullable<decimal> DiscInt { get; set; }
        public Nullable<decimal> UnpayDiscInt { get; set; }
        public Nullable<decimal> IntRate { get; set; }
        public Nullable<int> ReasonID { get; set; }
        public Nullable<decimal> AccInt { get; set; }
        public Nullable<decimal> YTDAccInt { get; set; }
        public Nullable<decimal> InstallAmt { get; set; }
        public Nullable<int> InstallMethodID { get; set; }
    
        public virtual LoanType LoanType { get; set; }
        public virtual Member Member { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<LoanDue> LoanDue { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MonthBalanceLoan> MonthBalanceLoan { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Security> Security { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TtlfLoan> TtlfLoan { get; set; }
    }
}
