//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Coop.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Member
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Member()
        {
            this.RequestLoan = new HashSet<RequestLoan>();
        }
    
        public Nullable<int> CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<int> ModifiedBy { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public string Filestatus { get; set; }
        public int CoopID { get; set; }
        public string MemberID { get; set; }
        public Nullable<int> TitleID { get; set; }
        public string Name { get; set; }
        public string Address { get; set; }
        public Nullable<int> SubDistrictID { get; set; }
        public Nullable<int> DistrictID { get; set; }
        public Nullable<int> ProvinceID { get; set; }
        public string PostalCode { get; set; }
        public string Telephone { get; set; }
        public string Mobile { get; set; }
        public string EMail { get; set; }
        public string IdCard { get; set; }
        public string LineID { get; set; }
        public Nullable<System.DateTime> BirthDate { get; set; }
        public Nullable<System.DateTime> ApplyDate { get; set; }
        public Nullable<System.DateTime> ResignDate { get; set; }
        public Nullable<decimal> Salary { get; set; }
        public Nullable<int> MemberGroupID { get; set; }
        public Nullable<int> MemberTypeID { get; set; }
        public Nullable<int> Sex { get; set; }
        public Nullable<int> DiscIntFlag { get; set; }
        public Nullable<int> MaritalStatus { get; set; }
    
        public virtual District District { get; set; }
        public virtual Province Province { get; set; }
        public virtual SubDistrict SubDistrict { get; set; }
        public virtual Title Title { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RequestLoan> RequestLoan { get; set; }
    }
}
