//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Coop.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class MilkText
    {
        public string MemberID { get; set; }
        public string FromDate { get; set; }
        public string ToDate { get; set; }
        public string PayDate { get; set; }
        public Nullable<decimal> AccountNo { get; set; }
        public Nullable<decimal> Receive { get; set; }
    }
}
