//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Coop.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class MonthBalanceLoan
    {
        public Nullable<int> CreateBy { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
        public Nullable<int> ModifiedBy { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public string Filestatus { get; set; }
        public int CoopID { get; set; }
        public string LoanID { get; set; }
        public string BudgetYear { get; set; }
        public int Period { get; set; }
        public string LoanTypeID { get; set; }
        public string MemberID { get; set; }
        public Nullable<decimal> BFBal { get; set; }
        public Nullable<decimal> LoanAmt { get; set; }
        public Nullable<decimal> Credit { get; set; }
        public Nullable<decimal> LoanBal { get; set; }
        public Nullable<decimal> LoanDueInYear { get; set; }
        public Nullable<decimal> CreditBeforeDue { get; set; }
        public Nullable<decimal> LoanDueDefault { get; set; }
        public Nullable<decimal> LoanDueNextYear { get; set; }
        public Nullable<decimal> LoanDue { get; set; }
        public Nullable<decimal> BFInt { get; set; }
        public Nullable<decimal> BFIntCredit { get; set; }
        public Nullable<decimal> IntCalcInYear { get; set; }
        public Nullable<decimal> IntCalcInYearCredit { get; set; }
        public Nullable<decimal> UnpayInt { get; set; }
        public Nullable<decimal> BFCharge { get; set; }
        public Nullable<decimal> BFChargeCredit { get; set; }
        public Nullable<decimal> ChargeCalcInYear { get; set; }
        public Nullable<decimal> ChargeCalcInYearCredit { get; set; }
        public Nullable<decimal> UnpayCharge { get; set; }
        public Nullable<decimal> BFDiscInt { get; set; }
        public Nullable<decimal> BFDiscIntCredit { get; set; }
        public Nullable<decimal> DiscIntCalcInYear { get; set; }
        public Nullable<decimal> DiscIntCalcInYearCredit { get; set; }
        public Nullable<decimal> UnpayDiscInt { get; set; }
    
        public virtual LoanType LoanType { get; set; }
        public virtual Loan Loan { get; set; }
        public virtual Member Member { get; set; }
    }
}
